// This file is no longer the primary source of data.
// It is kept to provide placeholder product information (like images)
// for the AI-generated orders.

import { PlaceHolderImages } from './placeholder-images';
import type { OrderItem } from './types';

// We still use this to get some product details for the AI-generated orders
export const products: Omit<OrderItem, 'quantity'>[] = PlaceHolderImages.map(p => ({
  id: p.id,
  name: p.description,
  price: parseFloat((Math.random() * 100 + 10).toFixed(2)),
  image: p.imageUrl,
  imageHint: p.imageHint,
}));

// The mockOrders array is no longer used by the application directly.
// The data is now generated by an AI flow in src/ai/flows/generate-sample-orders.ts
export const mockOrders: any[] = [];
